apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sdwqs1r3q-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sdwqs1r3q-java-quarkus-gitops